config/routes.rb
Rails.application.routes.draw do

  resources :companies do 
    resources :users do 
    end 

    resources :jobs do 
      resources :applicants do
        resources :applicantfiles do 
        end 
        resources :comments do
        end
      end

      put 'sort_applicants'
    end   
  end 

devise_scope :user do
  authenticated :user do
    root :to => 'home#index', :as => :root
  end
  
  unauthenticated :user do
    root :to =>  'devise/sessions#new', as: :unauthenticated_root
  end
end
devise_for :users, :controllers => { :invitations => "invitations"}

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id           :integer          not null, primary key
#  comment      :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :integer
#  applicant_id :integer
#

class Comment < ActiveRecord::Base

  belongs_to :applicant
  belongs_to :user
  scope :reverse_chron, -> {order('created_at DESC')}
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :fetch_company, :fetch_job, :fetch_applicant


  def new 
    @comment = @applicant.comments.new 
  end

  def create 
    @comment = @applicant.comments.new(comment_params)
    @user=current_user
    @comment_save = @comment.save    
    @comment.update_attribute(:user_id, current_user.id)

    
  end

  def show
  end

  def destroy     
    @comment = @applicant.comments.find(params[:id])
    @comment.destroy
  end 


  private 

    def fetch_job
      @job = @company.jobs.find(params[:job_id])
    end 

    def fetch_company 
      @company = Company.find(params[:company_id])
    end

    def fetch_applicant
      @applicant = @job.applicants.find(params[:applicant_id])
    end

    def comment_params
      params.require(:comment).permit(:comment)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>" class="comment_div">
  <p class="comment_commenter"><%= comment.user.name %>:</p>
  <p class="comment_text"><%= comment.comment %></p>
  <br>
  <p class="comment_created_time"><%= local_time(comment.created_at, '%l:%M%P, %b %e, %Y') %></p>  
  <%= link_to "Delete",  company_job_applicant_comment_path(@company, @job, @applicant, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true, class: "btn btn-danger pull-right", id: "delete_comment_button" %>
</div>      

app/views/comments/_new.html.erb
<div id="comment_entry_div">
  <%= simple_form_for [company, job, applicant, comment], remote: true do |f|%>
    <%= f.input :comment, as: :text, autofocus: true, input_html: {class: "comment_input"} %>
    <%= f.button :submit, "Save", class: "btn btn-success", id: "submit_comment" %>
  <% end %>
</div>

app/views/comments/create.js.erb
<% if @comment_save %>
  $('#applicant_details_<%= @applicant.id %> .modal-comment #all_comments').prepend('<%= j render(@comment) %>');
  $('.comment_input').val("");
<% end %>

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();