config/routes.rb
Rails.application.routes.draw do

  resources :companies do 
    resources :users do 
    end 

    resources :jobs do 
      resources :applicants do
        resources :applicantfiles do 
        end 
        resources :comments do
        end
      end

      put 'sort_applicants'
    end   
  end 

devise_scope :user do
  authenticated :user do
    root :to => 'home#index', :as => :root
  end
  
  unauthenticated :user do
    root :to =>  'devise/sessions#new', as: :unauthenticated_root
  end
end
devise_for :users, :controllers => { :invitations => "invitations"}

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  company_id  :integer
#

class Job < ActiveRecord::Base

  belongs_to :company
  validates :title, presence: true, length: {maximum: 140}
  has_many :applicants
  has_many :questions
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_company, only: [:index, :create, :new, :show, :destroy]
  before_action :fetch_job, only: [:show, :destroy]
  

  def new
    @job=current_user.company.jobs.new
  end

  def create
    @job=current_user.company.jobs.new(job_params)
    @job_save_success = @job.save
    
  end

  def show     
    @all_applicants  = @job.applicants.sort_by(&:position)

    @applicants_applied  = @all_applicants.select{|app| app.status == Applicant::Status::APPLIED}
    @applicants_shortlisted  = @all_applicants.select{|app| app.status == Applicant::Status::SHORTLISTED}
    @applicants_screening  = @all_applicants.select{|app| app.status == Applicant::Status::SCREENING}
    @applicants_prehire  = @all_applicants.select{|app| app.status == Applicant::Status::PREHIRE}
    @applicants_offered  = @all_applicants.select{|app| app.status == Applicant::Status::OFFERED}
    @applicants_rejected = @all_applicants.select{|app| app.status == Applicant::Status::REJECTED}

    @applicants_applied_count = @applicants_applied.count
    @applicants_shortlisted_count = @applicants_shortlisted.count
    @applicants_screening_count = @applicants_screening.count
    @applicants_prehire_count = @applicants_prehire.count
    @applicants_offered_count = @applicants_offered.count
    @applicants_rejected_count = @applicants_rejected.count

    @new_applicant = Applicant.new
  end 

  def index 
    @jobs = @company.jobs.all
    @new_job = Job.new
  end

  def destroy     
    @job.delete
    redirect_to company_jobs_path
  end

  def sort_applicants
    applicant_params = params[:applicant_ids]
    applicants = Applicant.where(id: applicant_params.values.flatten.collect(&:to_i)).group_by(&:id)
    applicant_params.each do |column_type, applicant_ids|
      column_type = column_type.to_i
      (0...applicant_ids.length).each do |i|
        applicants[applicant_ids[i].to_i][0].update_attributes(position: i+1, status: column_type)
      end
    end

    render nothing: true
  end


 
  private

  def job_params
    params.require(:job).permit(:title, :description)
  end

  def fetch_job 
    @job = Job.find(params[:id])
  end

  def fetch_company 
    @company = Company.find(params[:company_id])
  end
  
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>

  <div class="field input-group">
    <%= f.input :title, autofocus: true, placeholder: "Title" %>
  </div>

  <div class="field input-group">
    <%= f.input :description, placeholder: "Description", as: :text %>
  </div>

  <div class="actions input-group">
    <%= f.button :submit, "Create Job", class: "btn btn-primary", id: "create_job_btn" %>
  </div>

<% end %>

app/views/jobs/_job.html.erb
<div class="col-md-3 job_card_div">
  <%= link_to company_job_path(job.company, job), id: "job_card_clickable" do%>
    <div class="job_card">
      <p class="job_title"><%= job.title %></p>
      
    </div>
  <% end %>
</div>

app/views/jobs/_new.html.erb
<div class="applicant_add" data-toggle="modal" data-target="#new_job_myModal">
  <p id="add_job"><i class="fa fa-plus-square-o" id = "plus"></i>Add Job</p>
</div>




<div class="modal fade" id="new_job_myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a New Job</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [company, job], remote: true do |f| %>
          <div class="field input-group">
            <%= f.input :title, autofocus: true, placeholder: "Title" %>
          </div>

          <div class="field input-group">
            <%= f.input :description, placeholder: "Description", as: :text %>
          </div>

          <div class="actions input-group">
            <%= f.button :submit, "Create Job", class: "btn btn-primary", id: "create_job_btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/apply.html.erb
<div> 
  <h2><%= @job.title %></h2>
  <h4><%= @job.description %></h4>
  <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email" style="width:100px">
  <button class="btn btn-primary">Apply to this job</button>
</div>

app/views/jobs/create.js.erb
<% if @job_save_success %>
  $('#new_job_myModal').modal('hide');
  $('#jobs_div').append('<%= j render(@job) %>');
<% end %>

app/views/jobs/edit.html.erb
    <div class="container">
      <div class="row">
        <div class="col-sm-4 col-sm-offset-4">

          <%= render partial: 'jobs/form' %>



          <div id="questions">
          <div id="questions_list">
            <%= render @job.questions %>
          </div>
            <%= link_to "Add a question", new_job_question_path(@job), remote:true, class: "btn btn-primary", id: "add_question" %>
          </div>
        </div>
      </div>
    </div>

    

app/views/jobs/index.html.erb
<div class="container-fluid" id ="all_jobs_page">
  <div class="container" id="jobs_container">
    <div class="row" id ="jobs_div">
      <div class="col-md-3 job_card_div">    
        <div class="job_card">
          <%= render partial: 'jobs/new', locals: {company: @company, job: @new_job} %>  
        </div>        
      </div>
        <%= render(@jobs) %>
      </div>
  </div>
</div>  

app/views/jobs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">

      <%= simple_form_for [@company, @job] do |f| %>

      <div class="field input-group">
        <%= f.input :title, autofocus: true, placeholder: "Title" %>
      </div>

      <div class="field input-group">
        <%= f.input :description, placeholder: "Description", as: :text %>
      </div>

      <div class="actions input-group">
        <%= f.button :submit, "Create Job", class: "btn btn-primary", id: "create_job_btn" %>
      </div>

      <% end %>

    </div>
  </div>
</div>

    

app/views/jobs/show.html.erb
<div class="container-fluid" id ="job_dashboard_page">
  
  <div class="container-fluid">
    <div class="row" id ="jobs_div">      
      <h4 id="job_dashboard_title"><%= @job.title %></h4>     
         

      <div class="btn-group pull-right" id="job_edit_btn_group">
        <button type="button" class="btn btn-default dropdown-toggle" id = "job_edit_gear_toggle" data-toggle="dropdown" aria-expanded="false">    
          <span class="glyphicon glyphicon-cog"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Remove Job", company_job_path(@company, @job), method: :delete, id: "job_delete_btn", data: {confirm: "Are you sure?"} %></li>
        </ul>
      </div>  
    </div>


    <div class="row" id="job_dashboard_column_container">      
      <div class="col-md-2 job_dashboard_column_holder" id="job_dashboard_column_1">
        <div class="job_dashboard_column" id = "job_dashboard_column1">
          <h5> Applied : <span id="applicants_count_<%= Applicant::Status::APPLIED %>"><%= @applicants_applied_count %></span></h5>
          <div class="applicant_card">            
            <%= render partial: 'applicants/new', locals: {job: @job, company: @company, applicant: @new_applicant} %>            
          </div>
          <div class="applicants_container">
            <div id="applied_applicants" class="dashboard_column_list">            
                <% @applicants_applied.each do |applicant| %>
                  <%= render partial: 'applicants/applicant', locals: {applicant: applicant} %>
                <% end %>            
            </div>  
          </div>           
        </div>
      </div>





      <div class="col-md-2 job_dashboard_column_holder" id="job_dashboard_column_2">
        <div class="job_dashboard_column">
          <h5> Shortlisted : <span id="applicants_count_<%= Applicant::Status::SHORTLISTED %>"><%= @applicants_shortlisted_count %></span></h5>
          <div class="applicants_container">
            <div id="shortlisted_applicants" class="dashboard_column_list">            
                <% @applicants_shortlisted.each do |applicant| %>
                  <%= render partial: 'applicants/applicant', locals: {applicant: applicant} %>
                <% end %>            
            </div>  
          </div>
        </div>
      </div>




      <div class="col-md-2 job_dashboard_column_holder" id="job_dashboard_column_3">
        <div class="job_dashboard_column">
          <h5> Screening : <span id="applicants_count_<%= Applicant::Status::SCREENING %>"><%= @applicants_screening_count %></span></h5>
          <div class="applicants_container">
            <div id="screening_applicants" class="dashboard_column_list">            
                <% @applicants_screening.each do |applicant| %>
                  <%= render partial: 'applicants/applicant', locals: {applicant: applicant} %>
                <% end %>            
            </div> 
          </div>
        </div>
      </div>




      <div class="col-md-2 job_dashboard_column_holder" id="job_dashboard_column_4">
        <div class="job_dashboard_column">
          <h5> Pre-hire shortlist : <span id="applicants_count_<%= Applicant::Status::PREHIRE %>"><%= @applicants_prehire_count %></span></h5>
          <div class="applicants_container">
            <div id="prehire_applicants" class="dashboard_column_list">            
              <% @applicants_prehire.each do |applicant| %>
                <%= render partial: 'applicants/applicant', locals: {applicant: applicant} %>
              <% end %>            
            </div>
          </div> 
        </div>
      </div>



      <div class="col-md-2 job_dashboard_column_holder" id="job_dashboard_column_5">
        <div class="job_dashboard_column">
          <h5> Offered : <span id="applicants_count_<%= Applicant::Status::OFFERED %>"><%= @applicants_offered_count %></span></h5>
          <div class="applicants_container">
            <div id="offered_applicants" class="dashboard_column_list">            
              <% @applicants_offered.each do |applicant| %>
                <%= render partial: 'applicants/applicant', locals: {applicant: applicant} %>
              <% end %>            
            </div>
          </div> 
        </div>
      </div>  

      <div class="col-md-2 job_dashboard_column_holder" id="job_dashboard_column_7">
        <div class="job_dashboard_column">
          <h5> Rejected : <span id="applicants_count_<%= Applicant::Status::REJECTED %>"><%= @applicants_rejected_count %></span></h5>
          <div class="applicants_container">
            <div id="rejected_applicants" class="dashboard_column_list">            
              <% @applicants_rejected.each do |applicant| %>
                <%= render partial: 'applicants/applicant', locals: {applicant: applicant} %>
              <% end %>            
            </div>
          </div> 
        </div>
      </div> 

    </div>  
  </div>  
</div>  

<script type="text/javascript">
  $(document).ready(function() {
    console.log("Sorter Initialized");
    Sorter.makeSortable(<%= @company.id %>, <%= @job.id %>);
  });
</script>