config/routes.rb
Rails.application.routes.draw do

  resources :companies do 
    resources :users do 
    end 

    resources :jobs do 
      resources :applicants do
        resources :applicantfiles do 
        end 
        resources :comments do
        end
      end

      put 'sort_applicants'
    end   
  end 

devise_scope :user do
  authenticated :user do
    root :to => 'home#index', :as => :root
  end
  
  unauthenticated :user do
    root :to =>  'devise/sessions#new', as: :unauthenticated_root
  end
end
devise_for :users, :controllers => { :invitations => "invitations"}

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default("")
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime
#  updated_at             :datetime
#  company_id             :integer
#  name                   :string           default("Nonamion")
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_id          :integer
#  invited_by_type        :string
#  invitations_count      :integer          default("0")
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  
  belongs_to :company
  has_many :comments
  has_many :activities
  
  def accept_invitation
    super
    self.company = self.invited_by.company
    
  end


  def self.current=(user)
    Thread.current[:current_user] = user
  end

  def self.current
    Thread.current[:current_user]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :fetch_company, only: [:index]
  before_action :authenticate_user!, :fetch_user, only: [:destroy]

  def index
    @users = @company.users.all
  end
  
  def edit
  end
  
  def show 
  end

  def destroy     
    @user.delete
    redirect_to company_users_path
  end

  private
  
  def fetch_user 
    @user = User.find(params[:id])
  end
  def fetch_company 
    @company = Company.find(params[:company_id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container-fluid" id ="all_users_page">
  <div class="container" id="users_container">
    <div class="row" id ="users_div">
      <div class="col-md-3 user_card_div">    
        <div class="user_invite_card">
          <div id="invite_user_link">
          <p id="invite_user" data-toggle="modal" data-target="#invite_colleagues_myModal" ><i class="fa fa-plus-square-o" id = "plus"></i>Invite colleagues</p>
          </div>
        </div>
      </div>
      <% @users.each do |user| %>
        <div class="col-md-3 user_card_div">
          <div class="user_card">
            <% if user.invited_by_id != nil %>
            <%= link_to company_user_path(current_company ,user), method: :delete do %>
            <p id="remove_user"><i class="fa fa-times-circle-o"></i></p>
            <% end %>
            <% end %>
            <div class="user_card_details">
              <p class="user_card_name"><%= user.name.capitalize %></p>
              <p class="user_card_email"><%= user.email %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>



<div class="modal fade" id="invite_colleagues_myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" id="invite_colleagues_modal_dialog">
    <div class="modal-content" id="invite_colleagues_modal_content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Invite colleagues</h4>
      </div>
      <div class="modal-body">
        <div>
        <%= render "devise/invitations/new" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container" id ="user_settings">
  <div class="row">
    <div class="col-md-6">
      <h2 class="user_settings_header"> General Account settings </h2>
        <ul>
           <li class="user_name">
           <span class="settings_tag">Name:</span><%=current_user.name.capitalize  %>
           </li>
           <li class="user_email">
           <span class="settings_tag">Email:</span><%=current_user.email  %>
           </li>
           <li>
           <p class="edit_profile" data-toggle="modal" data-target="#edit_profile_myModal" > Edit profile</p>
           </li>            
        </ul>  
    </div>
  </div>
</div>



<!-- Modal for editing profile -->

<div class="modal fade" id="edit_profile_myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" id="invite_colleagues_modal_dialog">
    <div class="modal-content" id="invite_colleagues_modal_content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit profile</h4>
      </div>
      <div class="modal-body">
        <div>
        <%= render "devise/registrations/edit" %>
        </div>
      </div>
    </div>
  </div>
</div>